config/routes.rb
Rails.application.routes.draw do
 


 root "pubs#index"
 resources :pubs
 
end

app/models/pub.rb
class Pub < ActiveRecord::Base
	
	geocoded_by :address
	before_validation :geocode

	validates :title, presence: true, uniqueness: true
	validates :address, presence: true, uniqueness: true
	validates :latitude, presence: true, uniqueness: true
	validates :longitude, presence: true, uniqueness: true
	
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pubs_controller.rb
class PubsController < ApplicationController
	
	def index
		if params[:search].present? and params[:search][:q].present? and Pub.near[:search][:q].present?
			flash.now[:success] = "Pubs near #{params[:search][:q]}"
			@pubs = Pub.near(params[:search][:q])
		elsif params[:search].present? and params[:search][:q].present?
			flash.now[:error] = "Sorry we didn't find any Pubs near #{params[:search][:q]}"
			@pubs = Pub.all
		else
			@pubs = Pub.all
		end	
	end


	def new
		@pub = Pub.new
	end

	def create
		@pub = Pub.new(pub_params)
		if @pub.save

			flash[:success] = "Thank you for submitting a pub"
			redirect_to root_path

		else

			flash[:error] = "That's not a real place."
			render :new

		end
		
	end

private
	def pub_params
		params.require(:pub).permit(:title, :address, :latitude, :longitude)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pubs_helper.rb
module PubsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Appetite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header>
		<h1><%= link_to "Appetite", root_path %></h1>
		<p>The best Pubs in the world</p>
	</header>

<% flash.each do |key, value| %>

	<div class="<%= key %>">
		<p><%= value %></p>
	</div>
<% end %>


<%= yield %>

</body>
</html>

app/views/pubs/index.html.erb
<%= simple_form_for :search, url: root_path, method: :get do |f| %>
	<%= f.input :q, label: false %>
<% end %>

<ul>

	<% @pubs.each do |pub| %>

		<li data-lat='<%= pub.latitude %>' data-lng='<%= pub.longitude%>'>

			<p><%= pub.title %></P>
			<p><%= pub.address %></P>
		</li>
	<% end %>

</ul>

<section id="map"></section>

<%= link_to "Add a pub", new_pub_path, class: 'button' %>  

app/views/pubs/new.html.erb
<%= simple_form_for @pub do |p| %>

	<%= p.input :title %>
	<%= p.input :address %>
	<%# p.input :latitude %>
	<%# p.input :longitude %>
	
	<%= p.button :submit, "Add a pub" %>

<% end %>